Algoritmo "Número Aleatório"
// Função: Decidir se um número é ou não maior que 10
// Turma: 1ºC
// Autor(a)    : Bryan Almeida de Moraes
// Data atual  : 18/05/2023
Var
// Seção de Declarações das variáveis 
numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um numero: ")
leia(numero)

se(numero>10)entao
     escreval("Parabens, esse numero e maior que 10")
senao
     escreval("Nao, voce errou...")
fimse

Fimalgoritmo