algoritmo "Conversão de Celsius em Fahrenheit"
// Disciplina: PA
// Professora: Cintia
// Turma: 1ºC
// Nome: Bryan Almeida de Moraes
// Data: 09/03/2023
var
F,C: real

inicio
// entrada
escreval("Diga quantos graus em celsius deseja calcular: ")
leia(C)

// processamento
F<- (9*C+ 160)/5

// saída
escreval("-----------------------------------------------")
escreval(C," graus Celsius é igual a ",F," graus fahrenheit")

fimalgoritmo
